#!/usr/bin/env python3
"""
NeuronOS — Embed Web UI into C header

Reads webui/index.html, optionally gzips it, and generates a C header
with the data as an unsigned char array.

Usage:
  python3 embed_webui.py [--gzip] <input.html> <output.h>

The generated header can be included directly by neuronos_server.c.
This script is called by CMake at build time, but the generated output
is also committed to the repo so builds work without Python.
"""

import sys
import os
import gzip as gz

def main():
    use_gzip = False
    args = [a for a in sys.argv[1:] if not a.startswith('-')]
    if '--gzip' in sys.argv:
        use_gzip = True

    if len(args) < 2:
        print(f"Usage: {sys.argv[0]} [--gzip] <input.html> <output.h>", file=sys.stderr)
        sys.exit(1)

    input_path = args[0]
    output_path = args[1]

    # Read input
    with open(input_path, 'rb') as f:
        data = f.read()

    raw_size = len(data)

    # Optionally gzip
    if use_gzip:
        data = gz.compress(data, compresslevel=9)

    # Generate C header
    var_suffix = '_gz' if use_gzip else ''
    var_name = f'neuronos_chat_ui_html{var_suffix}'

    lines = []
    lines.append('/* Auto-generated by embed_webui.py — DO NOT EDIT */')
    lines.append(f'/* Source: {os.path.basename(input_path)} ({raw_size} bytes raw'
                 f'{f", {len(data)} bytes gzipped" if use_gzip else ""}) */')
    lines.append('')
    lines.append('#ifndef NEURONOS_CHAT_UI_DATA_H')
    lines.append('#define NEURONOS_CHAT_UI_DATA_H')
    lines.append('')
    lines.append(f'static const unsigned char {var_name}[] = {{')

    # Write data as hex bytes, 16 per line
    for i in range(0, len(data), 16):
        chunk = data[i:i+16]
        hex_vals = ','.join(f'0x{b:02x}' for b in chunk)
        lines.append(f'  {hex_vals},')

    lines.append('};')
    lines.append(f'static const unsigned int {var_name}_len = {len(data)};')

    if use_gzip:
        lines.append(f'static const unsigned int neuronos_chat_ui_html_raw_len = {raw_size};')
        lines.append(f'#define NEURONOS_CHAT_UI_IS_GZIPPED 1')
    else:
        lines.append(f'#define NEURONOS_CHAT_UI_IS_GZIPPED 0')

    lines.append('')
    lines.append('#endif /* NEURONOS_CHAT_UI_DATA_H */')
    lines.append('')

    # Write output
    os.makedirs(os.path.dirname(output_path) or '.', exist_ok=True)
    with open(output_path, 'w') as f:
        f.write('\n'.join(lines))

    print(f"Embedded {os.path.basename(input_path)} -> {os.path.basename(output_path)} "
          f"({raw_size} -> {len(data)} bytes{' gzipped' if use_gzip else ''})")

if __name__ == '__main__':
    main()
