name: Bug Report
description: Report a bug or unexpected behavior
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting! Please fill out the details below.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: What happened? What did you expect?
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: Minimal steps to trigger the issue
      placeholder: |
        1. neuronos agent "..."
        2. Observe error
    validations:
      required: true

  - type: textarea
    id: hwinfo
    attributes:
      label: Hardware info
      description: Paste output of `neuronos hwinfo`
      render: text

  - type: input
    id: version
    attributes:
      label: NeuronOS version
      placeholder: "0.9.1"

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - Linux x86_64
        - Linux ARM64
        - macOS ARM64 (Apple Silicon)
        - macOS x86_64
        - Windows x64 (WSL)
        - Windows x64 (native)
        - Android
        - Other
