name: Feature Request
description: Suggest a new feature or improvement
labels: ["enhancement"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What feature would you like to see?
    validations:
      required: true

  - type: textarea
    id: use_case
    attributes:
      label: Use case
      description: How would you use this feature?

  - type: dropdown
    id: area
    attributes:
      label: Area
      options:
        - Agent / ReAct loop
        - Memory system
        - Model support
        - MCP (server or client)
        - CLI / UX
        - HTTP API
        - Hardware / HAL
        - Packaging / Install
        - Documentation
        - Other
