/* ============================================================
 * NeuronOS — Embedded Chat UI (HTML/CSS/JS)
 *
 * Single-page chat interface served at GET / when in agent mode.
 * Talks to POST /api/chat for agent interaction (SSE streaming).
 * Zero external dependencies — all inline.
 * ============================================================ */
#ifndef NEURONOS_CHAT_UI_H
#define NEURONOS_CHAT_UI_H

static const char NEURONOS_CHAT_UI_HTML[] =
    "<!DOCTYPE html>\n"
    "<html lang=\"en\">\n"
    "<head>\n"
    "<meta charset=\"UTF-8\">\n"
    "<meta name=\"viewport\" content=\"width=device-width,initial-scale=1.0\">\n"
    "<title>NeuronOS</title>\n"
    "<style>\n"
    "*{margin:0;padding:0;box-sizing:border-box}\n"
    ":root{--bg:#0a0a0f;--surface:#111118;--border:#1e1e2e;--text:#e0e0e0;\n"
    "  --dim:#888;--accent:#00ffd5;--accent2:#00bcd4;--user-bg:#1a3a5c;\n"
    "  --user-border:#2a5a8c;--bot-bg:#1a1a24;--bot-border:#2a2a3e;\n"
    "  --yellow:#fbbf24;--green:#4ade80;--radius:12px}\n"
    "body{font-family:'SF Mono','Fira Code','JetBrains Mono','Cascadia Code',\n"
    "  'Consolas',monospace;background:var(--bg);color:var(--text);\n"
    "  height:100vh;display:flex;flex-direction:column;overflow:hidden}\n"
    /* ─── Header ─── */
    ".hdr{background:var(--surface);border-bottom:1px solid var(--border);\n"
    "  padding:14px 24px;display:flex;align-items:center;gap:12px;\n"
    "  flex-shrink:0}\n"
    ".hdr .logo{color:var(--accent);font-size:18px;font-weight:700}\n"
    ".hdr .ver{color:#555;font-size:12px}\n"
    ".hdr .st{margin-left:auto;display:flex;align-items:center;gap:8px;\n"
    "  color:var(--green);font-size:12px}\n"
    ".hdr .st::before{content:'';width:8px;height:8px;\n"
    "  background:var(--green);border-radius:50%;display:inline-block}\n"
    /* ─── Chat area ─── */
    ".chat{flex:1;overflow-y:auto;padding:24px;display:flex;\n"
    "  flex-direction:column;gap:16px;scroll-behavior:smooth}\n"
    ".msg{max-width:80%;padding:12px 16px;border-radius:var(--radius);\n"
    "  line-height:1.65;white-space:pre-wrap;word-wrap:break-word;\n"
    "  animation:fadeIn .25s ease}\n"
    "@keyframes fadeIn{from{opacity:0;transform:translateY(8px)}to{opacity:1;transform:none}}\n"
    ".msg.user{align-self:flex-end;background:var(--user-bg);\n"
    "  border:1px solid var(--user-border);color:#c0e0ff}\n"
    ".msg.bot{align-self:flex-start;background:var(--bot-bg);\n"
    "  border:1px solid var(--bot-border)}\n"
    ".msg .step{font-size:12px;margin-top:8px;padding-top:8px;\n"
    "  border-top:1px solid var(--bot-border)}\n"
    ".msg .step .think{color:var(--yellow)}\n"
    ".msg .step .tool{color:var(--accent2)}\n"
    ".msg .step .obs{color:var(--dim);font-size:11px}\n"
    /* ─── Typing indicator ─── */
    ".typing{align-self:flex-start;background:var(--bot-bg);\n"
    "  border:1px solid var(--bot-border);border-radius:var(--radius);\n"
    "  padding:12px 20px;display:none;gap:5px;align-items:center}\n"
    ".typing.on{display:flex}\n"
    ".typing span{width:7px;height:7px;background:var(--accent);border-radius:50%;\n"
    "  animation:bounce .6s infinite alternate}\n"
    ".typing span:nth-child(2){animation-delay:.2s}\n"
    ".typing span:nth-child(3){animation-delay:.4s}\n"
    "@keyframes bounce{to{opacity:.3;transform:translateY(-4px)}}\n"
    /* ─── Steps live feed ─── */
    ".live-steps{align-self:flex-start;font-size:12px;\n"
    "  color:var(--dim);padding:4px 16px;display:none}\n"
    ".live-steps.on{display:block}\n"
    ".live-steps .ls-think{color:var(--yellow)}\n"
    ".live-steps .ls-tool{color:var(--accent2)}\n"
    /* ─── Input area ─── */
    ".inp{background:var(--surface);border-top:1px solid var(--border);\n"
    "  padding:16px 24px;display:flex;gap:12px;flex-shrink:0}\n"
    ".inp textarea{flex:1;background:#0a0a14;border:1px solid var(--bot-border);\n"
    "  border-radius:8px;color:var(--text);font-family:inherit;font-size:14px;\n"
    "  padding:11px 14px;resize:none;height:44px;max-height:140px;outline:none;\n"
    "  transition:border-color .2s}\n"
    ".inp textarea:focus{border-color:var(--accent)}\n"
    ".inp button{background:var(--accent);color:var(--bg);border:none;\n"
    "  border-radius:8px;padding:0 24px;font-family:inherit;font-size:14px;\n"
    "  font-weight:700;cursor:pointer;transition:opacity .2s;flex-shrink:0}\n"
    ".inp button:hover{opacity:.85}\n"
    ".inp button:disabled{opacity:.35;cursor:not-allowed}\n"
    /* ─── Welcome ─── */
    ".welcome{text-align:center;padding:60px 20px;color:var(--dim)}\n"
    ".welcome h2{color:var(--accent);font-size:24px;margin-bottom:12px}\n"
    ".welcome p{max-width:500px;margin:0 auto;line-height:1.7;font-size:14px}\n"
    ".welcome .caps{display:flex;flex-wrap:wrap;gap:8px;justify-content:center;\n"
    "  margin-top:20px}\n"
    ".welcome .cap{background:var(--bot-bg);border:1px solid var(--bot-border);\n"
    "  border-radius:6px;padding:6px 12px;font-size:12px;color:var(--accent2)}\n"
    /* ─── Scrollbar ─── */
    "::-webkit-scrollbar{width:6px}\n"
    "::-webkit-scrollbar-track{background:transparent}\n"
    "::-webkit-scrollbar-thumb{background:#333;border-radius:3px}\n"
    "@media(max-width:600px){\n"
    "  .msg{max-width:92%}\n"
    "  .inp{padding:12px}\n"
    "  .chat{padding:16px}\n"
    "}\n"
    "</style>\n"
    "</head>\n"
    "<body>\n"
    "<div class=\"hdr\">\n"
    "  <span class=\"logo\">&#9889; NeuronOS</span>\n"
    "  <span class=\"ver\" id=\"ver\"></span>\n"
    "  <span class=\"st\">Local &bull; Offline</span>\n"
    "</div>\n"
    "<div class=\"chat\" id=\"chat\">\n"
    "  <div class=\"welcome\" id=\"welcome\">\n"
    "    <h2>&#9889; NeuronOS Agent</h2>\n"
    "    <p>AI agent running 100%% locally on your device.<br>\n"
    "    No cloud. No data leaves your machine. Ever.</p>\n"
    "    <div class=\"caps\">\n"
    "      <span class=\"cap\">&#128736; Tool Use</span>\n"
    "      <span class=\"cap\">&#129504; Reasoning</span>\n"
    "      <span class=\"cap\">&#128190; Memory</span>\n"
    "      <span class=\"cap\">&#128193; Files</span>\n"
    "      <span class=\"cap\">&#127760; Web</span>\n"
    "      <span class=\"cap\">&#128187; Shell</span>\n"
    "    </div>\n"
    "  </div>\n"
    "</div>\n"
    "<div class=\"live-steps\" id=\"live\"></div>\n"
    "<div class=\"typing\" id=\"typing\">\n"
    "  <span></span><span></span><span></span>\n"
    "</div>\n"
    "<div class=\"inp\">\n"
    "  <textarea id=\"input\" placeholder=\"Ask anything...\" rows=\"1\"\n"
    "    onkeydown=\"if(event.key==='Enter'&&!event.shiftKey){event.preventDefault();sendMsg()}\"\n"
    "    oninput=\"this.style.height='44px';this.style.height=Math.min(this.scrollHeight,140)+'px'\"\n"
    "  ></textarea>\n"
    "  <button id=\"btn\" onclick=\"sendMsg()\">Send</button>\n"
    "</div>\n"
    "<script>\n"
    "const chat=document.getElementById('chat');\n"
    "const input=document.getElementById('input');\n"
    "const btn=document.getElementById('btn');\n"
    "const typing=document.getElementById('typing');\n"
    "const live=document.getElementById('live');\n"
    "const welcome=document.getElementById('welcome');\n"
    "let busy=false;\n"
    "\n"
    "/* Fetch version */\n"
    "fetch('/health').then(r=>r.json()).then(d=>{\n"
    "  document.getElementById('ver').textContent='v'+d.version;\n"
    "}).catch(()=>{});\n"
    "\n"
    "function esc(s){const d=document.createElement('div');d.textContent=s;return d.innerHTML}\n"
    "\n"
    "function addMsg(role,text,steps){\n"
    "  if(welcome.style.display!=='none') welcome.style.display='none';\n"
    "  const div=document.createElement('div');\n"
    "  div.className='msg '+role;\n"
    "  let html=esc(text);\n"
    "  if(steps&&steps.length){\n"
    "    html+='<div class=\"step\">';\n"
    "    steps.forEach(s=>{\n"
    "      if(s.type==='thinking') html+='<div class=\"think\">[thinking] '+esc(s.text)+'</div>';\n"
    "      else if(s.type==='tool') html+='<div class=\"tool\">[tool: '+esc(s.name)+']</div>';\n"
    "      else if(s.type==='observation') html+='<div class=\"obs\">'+esc(s.text.substring(0,300))+'</div>';\n"
    "    });\n"
    "    html+='</div>';\n"
    "  }\n"
    "  div.innerHTML=html;\n"
    "  chat.appendChild(div);\n"
    "  chat.scrollTop=chat.scrollHeight;\n"
    "}\n"
    "\n"
    "async function sendMsg(){\n"
    "  if(busy)return;\n"
    "  const text=input.value.trim();\n"
    "  if(!text)return;\n"
    "  input.value='';input.style.height='44px';\n"
    "  addMsg('user',text);\n"
    "  busy=true;btn.disabled=true;\n"
    "  typing.classList.add('on');\n"
    "  live.innerHTML='';live.classList.add('on');\n"
    "  chat.scrollTop=chat.scrollHeight;\n"
    "\n"
    "  let steps=[];\n"
    "  let response='';\n"
    "  try{\n"
    "    const res=await fetch('/api/chat',{\n"
    "      method:'POST',\n"
    "      headers:{'Content-Type':'application/json'},\n"
    "      body:JSON.stringify({message:text})\n"
    "    });\n"
    "    const reader=res.body.getReader();\n"
    "    const decoder=new TextDecoder();\n"
    "    let buf='';\n"
    "    while(true){\n"
    "      const{done,value}=await reader.read();\n"
    "      if(done)break;\n"
    "      buf+=decoder.decode(value,{stream:true});\n"
    "      let lines=buf.split('\\n');\n"
    "      buf=lines.pop();\n"
    "      for(const line of lines){\n"
    "        if(!line.startsWith('data: '))continue;\n"
    "        const payload=line.slice(6);\n"
    "        if(payload==='[DONE]')continue;\n"
    "        try{\n"
    "          const ev=JSON.parse(payload);\n"
    "          if(ev.type==='thinking'){\n"
    "            steps.push(ev);\n"
    "            live.innerHTML='<span class=\"ls-think\">[thinking] '+esc(ev.text)+'</span>';\n"
    "          }else if(ev.type==='tool'){\n"
    "            steps.push(ev);\n"
    "            live.innerHTML='<span class=\"ls-tool\">[tool: '+esc(ev.name)+'] '+esc(ev.args||'')+'</span>';\n"
    "          }else if(ev.type==='observation'){\n"
    "            steps.push(ev);\n"
    "            live.innerHTML='<span class=\"ls-tool\">[result] '+esc(ev.text.substring(0,120))+'</span>';\n"
    "          }else if(ev.type==='response'){\n"
    "            response=ev.text;\n"
    "          }else if(ev.type==='error'){\n"
    "            response='[Error] '+(ev.text||'Agent error');\n"
    "          }\n"
    "        }catch(e){}\n"
    "      }\n"
    "    }\n"
    "  }catch(e){\n"
    "    response='[Connection error] '+e.message;\n"
    "  }\n"
    "  typing.classList.remove('on');\n"
    "  live.classList.remove('on');live.innerHTML='';\n"
    "  if(response) addMsg('bot',response,steps);\n"
    "  busy=false;btn.disabled=false;\n"
    "  input.focus();\n"
    "}\n"
    "\n"
    "input.focus();\n"
    "</script>\n"
    "</body></html>\n";

#endif /* NEURONOS_CHAT_UI_H */
